### ISSUE TITLE
Line in userContent.css affects websites

### ISSUE THREAD

**Issue by loopy750** [CristianDragos/FirefoxThemes#1]
(Might be easier to report things here than continue on Reddit :))

Using the line `@import "userChrome.css";` can affect websites with the same ids/classes. For example `.search-box` affects Twitch and any other website using that class.

I'm guessing its purpose is just to import the variables from userChrome? Thanks.

**Comment by dpcdpc11** [comment]
That's correct. My initial "object oriented" approach was to create a
separate file, something like variables.css, where I would store the
variables, and then @import that into both userchrome.css and
usercontent.css.
But I didn't want to make things too complicated for the users so I stuck
to two files instead.
I didn't think that those classes could affect websites so thanks
for pointing that out!
I see two options here:
1) target those classes more specifically using ">"
2) just add the variables to usercontent.css as well.

What do you think? Any thoughts or a better solution?

Thanks!

**Comment by loopy750** [comment]
To be honest I'm not sure what this usercontent.css changes. I used to use that file before Firefox had a dark theme for all the about: pages, but I don't see much of a need now. I'm guessing simply copying those variables from userchrome would be the safest option...

**Comment by dpcdpc11** [comment]
The usercontent.css customizes the New Tab page which has a built in search
dialog and there are also the drop-down search results.
By default with Windows Dark mode on these look okay but they don't match
the same gray tones I used in my userchrome.css so people that are using
this were complaining about not being themed properly and using that
usercontent.css is the only way to do it since the CSS from userchrome.css
doesn't apply unfortunately.

After doing a bit of thinking, I'll definitely go with the second option to
fix the problem.

**Comment by dpcdpc11** [comment]
I've ended up adding the color variables into the userContent.css file and made a few changes to a few of the elements.
